### ISSUE TITLE
Erro ao importar Usando o Composer

### ISSUE THREAD

**Issue by alvarolordelo** [newerton/yii2-boleto-remessa#1]
![image](https://user-images.githubusercontent.com/1663952/29788007-665d928c-8c07-11e7-8d33-53c7feb81e99.png)

Ao se inserir o comando o mesmo diz que não encontra uma versão com uma estabilidade.

**Comment by newerton** [comment]
O seu composer o minimum-stability está "stable" ? Se sim, muda para "dev".
