### ISSUE TITLE
Bancoob - SICOOB

### ISSUE THREAD

**Issue by ctoigo** [newerton/yii2-boleto-remessa#10]
O arquivo remessa não é mais valido o modelo CNAB 400. Este modelo não é mais aceito para novas homologações, pois agora o padrão Febraban é o CNAB 240.

Outro detalhe.
No código do beneficiário está o número da conta corrente, porém neste campo precisa estar aparecendo o código do cliente.

Com estas correções já é possível homologar no SICOOB.

**Comment by ctoigo** [comment]
Só estou vendo o esquema do boleto, pois no arquivo AbstractBoleto tem a função: getAgenciaCodigoBeneficiario(), porém ela é generica, o que precisaria ver como vc quer tratar ela para tratar situações especificas como no caso do SICOOB.

**Comment by newerton** [comment]
Mas você não consegue setar o código do cliente no getAgenciaCodigoBeneficiario() ?

**Comment by ctoigo** [comment]
Dentro da função vc tem assim:

        $agencia = $this->getAgenciaDv() !== null ? $this->getAgencia() . '-' . $this->getAgenciaDv() : $this->getAgencia();
        $conta = $this->getContaDv() !== null ? $this->getConta() . '-' . $this->getContaDv() : $this->getConta();

**Comment by newerton** [comment]
@ctoigo Pode criar um getCodigoBeneficiario() ou getCodigoCliente(), especifico para o SICOOB.

**Comment by ctoigo** [comment]
Ok, vou verificar como resolver aqui.

**Comment by ctoigo** [comment]
Estou tendo o seguinte retorno.

$a não possui 240 posições, possui: 0 

Pode me ajudar a descobrir o que é?

**Comment by ctoigo** [comment]
Já consegui resolver.

**Comment by newerton** [comment]
Eu já ia pedir os dados do boleto! Que bom que resolveu, está 100% agora?

**Comment by ctoigo** [comment]
Já está indo para homologação no Banco.
