### ISSUE TITLE
Gerar disconto no boleto BB

### ISSUE THREAD

**Issue by alvarolordelo** [newerton/yii2-boleto-remessa#2]
Estou tentando gerar um boleto que tenha um valor menor até a data de vencimento e a partir do dia apos o vencimento o valor cheio
Exemplo:
boleto com valor de 200,00 até 11.09.2017
e após esta data 250,00.
no array de configuração não achei esse campo.

**Comment by newerton** [comment]
@alvarolordelo O correto e você colocar o valor cheio, e colocar nas Instruções um desconto, ou você pode colocar o valor já com desconto, e depois do vencimento você coloca nas instruções para acrescentar mais X reais de multa.

O boleto não se gera 2 códigos de barra, é gerado 1 código de barra, e nas instruções você informa os valores antes e/ou depois do vencimento. O boleto só aceita 1 valor no código de barras.

Se você não está achando os campos de instruções. Ele é adicionado no array, do qual é gerado o boleto.

**Comment by alvarolordelo** [comment]
Bom, eu estou aqui tentando te entender.
01 - quando colocamos na intrução um valor menor o codigo de barras aparece o valor menor ?
02 - a minha meta é se esta no dia do vencimento cobrar valor 200 senão cobrar 250
visto que geralmente paga-se pelo celular e este pega o valor automaticamente.
você compreendeu minha duvida ?
qual seria o campo que colocaria o valor de 200 e o de 250 pra que caso a data fosse maior que a data de vencimento o valor automaticamente fosse reconhecido pelo leitor do celular.

**Comment by newerton** [comment]
Entendi sua situação.

Então nesse caso, você tem que colocar o valor cheio. E nas instruções informa se pagar antes da data de vencimento, é concedido o desconto de R$50,00.

Nenhum app ou internet banking recalcula isso automaticamente.

Vou te dar um exemplo real, eu pago X de aluguel, mais a imobiliária concede 83 reais de desconto, se eu pagar antes do vencimento. Só que não cheguei na situação de pagar atrasado, para ver se o app ou internet banking permite adicionar o desconto depois do vencimento, e também não sei se ambos permite trocar o valor no boleto depois do vencimento.

**Comment by alvarolordelo** [comment]
01 - No boleto tem lá os campos desconto, valor cobrado, multa etc...
como faço pra passar isso no array ?

02 - você não implementou ou não existe esse remessa 240 do BB ?
Obrigado por responder minhas duvidas.

**Comment by newerton** [comment]
Na página principal do repositório tem um exemplo para gerar um boleto no Banco do Brasil.

```php
$boletoArray = [
	'logo' => 'path/para/o/logo', // Logo da empresa
	'dataVencimento' => new \Carbon\Carbon('1790-01-01'),
	'valor' => 100.00,
	'multa' => 10.00, // porcento
	'juros' => 2.00, // porcento ao mes
	'juros_apos' =>  1, // juros e multa após
	'diasProtesto' => false, // protestar após, se for necessário
	'numero' => 1,
	'numeroDocumento' => 1,
	'pagador' => $pagador, // Objeto PessoaContract
	'beneficiario' => $beneficiario, // Objeto PessoaContract
	'agencia' => 9999, // BB, Bradesco, CEF, HSBC, Itáu
	'agenciaDv' => 9, // se possuir
	'conta' => 99999, // BB, Bradesco, CEF, HSBC, Itáu, Santander
	'contaDv' => 9, // Bradesco, HSBC, Itáu
	'carteira' => 99, // BB, Bradesco, CEF, HSBC, Itáu, Santander
	'convenio' => 9999999, // BB
	'variacaoCarteira' => 99, // BB
	'range' => 99999, // HSBC
	'codigoCliente' => 99999, // Bradesco, CEF, Santander
	'ios' => 0, // Santander
	'descricaoDemonstrativo' => ['msg1', 'msg2', 'msg3'], // máximo de 5
	'instrucoes' =>  ['inst1', 'inst2'], // máximo de 5
	'aceite' => 1,
	'especieDoc' => 'DM',
];

$boleto = new \Newerton\Yii2Boleto\Boleto\Banco\Bb($boletoArray);```


Sobre a remessa existe mais não foi implementada, pode ficar livre para clonar o repositorio e implementar. E que nunca trabalhei com remessa 240 do BB.

Se você tiver a documentação, será facil criar a remessa 240 pelo outros códigos do banco.

**Comment by alvarolordelo** [comment]
Não teria que ter um campo desconto não ? pra poder colocar o valor?

**Comment by newerton** [comment]
Tem sim, pode usar:
```
'desconto' => 50.00,
```

**Comment by alvarolordelo** [comment]
A duvida foi sanada, neste momento gostaria de saber se é possivel gerar o boleto sem a parte superior de demostrativo.
Gostaria de ter apenas o canhoto com a parte do pagador. caso não fique claro a pergunta me avisa.
Obrigado pelo excelente trabalho.
