### ISSUE TITLE
Erro de envio de remessa Banco Caixa Economica Federal

### ISSUE THREAD

**Issue by alvarolordelo** [newerton/yii2-boleto-remessa#3]
Após o envio de remessa são mostrados erros em alguns campos
e também erro de cabeçalho, erro de contagem de registros;
estou usando caixa economica federal Cnab400 Carteira Registrada
![20180123_152935](https://user-images.githubusercontent.com/1663952/35293755-70266238-0053-11e8-994c-a32b9aa19411.jpg)
![20180123_153050](https://user-images.githubusercontent.com/1663952/35293836-ac9f4112-0053-11e8-8750-6ef540783b3a.jpg)

**Comment by newerton** [comment]
@alvarolordelo Você tem a documentação do Caixa Econômica para gerar a Remessa? Cria um fork, faz a alteração da remessa e me envia um PR. Com a Caixa faz muito tempo que trabalhei com ela, não sei se a documentação está atualizada.

**Comment by alvarolordelo** [comment]
http://www.caixa.gov.br/Downloads/cobranca-caixa/Manual_Leiaute_CNAB400_SIGCB.pdf
