### ISSUE TITLE
Erro Declaration of Carbon\Carbon::diffInDaysFiltered no Cakephp 3

### ISSUE THREAD

**Issue by lucianolopezz** [newerton/yii2-boleto-remessa#38]
Estou recebendo este erro ao tentar usar no Cakephp 3:

Fatal error: Declaration of Carbon\Carbon::diffInDaysFiltered(Closure $callback, $date = NULL, $absolute = true) must be compatible with Cake\Chronos\ChronosInterface::diffInDaysFiltered(callable $callback, ?Cake\Chronos\ChronosInterface $dt = NULL, $abs = true) in **C:\xampp\htdocs\pro_oftalmo_prontuario\vendor\nesbot\carbon\src\Carbon\Carbon.php on line 216**

**Comment by newerton** [comment]
@lucianolopezz esse método não é usado na biblioteca de gerar boleto, executa um composer update para atualizar, e verificar se não tem outra biblioteca alterando a versão do Carbon no composer.

Essa biblioteca de gerar boleto usa a versão 2 do Carbon, e pela linha do erro, na classe do Carbon essa linha é comentário.
https://github.com/briannesbitt/Carbon/blob/2.38.0/src/Carbon/Carbon.php#L216

**Comment by lucianolopezz** [comment]
@newerton Substitui o Carbon, Pelo Cake\I18n\Time e aparentemente deu certo para gerar boleto com Pdf.
Você me autoriza a adaptar essa lib para Cakephp e disponibiliza-la para comunidade ?

**Comment by newerton** [comment]
> @newerton Substitui o Carbon, Pelo Cake\I18n\Time e aparentemente deu certo para gerar boleto com Pdf.
> Você me autoriza a adaptar essa lib para Cakephp e disponibiliza-la para comunidade ?

@lucianolopezz fica a vontade, eu fiz essa lib em cima de outra feita em Laravel. Quanto mais lib para cada framework existir é melhor para todos. Quando desenvolver me comunica que quero acompanhar.

**Comment by lucianolopezz** [comment]
@newerton combinado!
