### ISSUE TITLE
Erro na Instalaçao

### ISSUE THREAD

**Issue by sergiorn20002** [newerton/yii2-boleto-remessa#39]
Boa tarde, estou com problemas na instalaçao, gostaria de um suporte a mensagem de erro e o seguinte:
C:\Composer>composer require newerton/yii2-boleto-remessa": "dev-master"
./composer.json has been updated
Running composer update newerton/yii2-boleto-remessa
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing newerton/yii2-boleto-remessa (dev-master 9e7974e): Cloning 9e7974eb8e
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+SAPINFOMATICA+2021-01-25+1800
to retrieve a token. It will be stored in "C:/Users/SapInformatica/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by alvarolordelo** [comment]
Problema de key na api gitbut irmão, melhor clicar no link e atulizar o mecanismo, veja se o composer ta na versão 2.0 ou acima.
Fica tranquilo que é coisa simples, essa mensagem quer o token de autenticação da API.
Se já resolveu muda o status da issue.
