### ISSUE TITLE
Retorno gerando call of undefined function ao instanciar a classe

### ISSUE THREAD

**Issue by alvarolordelo** [newerton/yii2-boleto-remessa#40]
![image](https://user-images.githubusercontent.com/1663952/153081973-0c9d5c81-7a2a-478c-9f64-21c95bba2aff.png)

Função array_get() não encontrada.. Ela depende de que pacote?
vi que ela é usada no Laravel...de todo modo ela ta quebrando a classe.
Parabéns pelo ótimo trabalho no pacote de boletos.

**Comment by newerton** [comment]
@alvarolordelo Esse projeto, foi um clone do repositório de boleto do laravel.
Verifiquei aqui o que essa função faz no Laravel, e vou enviar uma correção.

**Comment by alvarolordelo** [comment]
> 

Amigo, eu já corrigi...é só mudar para 
array_column
linha 242
->setOcorrenciaDescricao(array_column($this->ocorrencias, $d->getOcorrencia(), 'Desconhecida'))

**Comment by alvarolordelo** [comment]
podem haver mais erros..eu só corrigi ai por ser pontual..tava vendo como criar um PR pra ajudar no seu projeto.

**Comment by alvarolordelo** [comment]
Gerei um Pull Request pra você analisar se tá ok.

**Comment by alvarolordelo** [comment]
https://laravel.com/docs/5.2/helpers#method-array-get
 Referência do laravel.

**Comment by alvarolordelo** [comment]
> @alvarolordelo Esse projeto, foi um clone do repositório de boleto do laravel. Verifiquei aqui o que essa função faz no Laravel, e vou enviar uma correção.

https://laravel.com/docs/5.2/helpers#method-array-get

https://www.w3schools.com/php/func_array_column.asp

**Comment by newerton** [comment]
@alvarolordelo Testa esse novo update que fiz no repositorio.

Criei uma trait para usar nos outros bancos.

https://github.com/newerton/yii2-boleto-remessa/blob/master/src/Traits/ArrayHelper.php
