### ISSUE TITLE
Problemas com data em boletos acima de 1

### ISSUE THREAD

**Issue by nicholaskr** [newerton/yii2-boleto-remessa#6]
Estou tendo um problema com datas quando emito mais de 1 boleto por vez... segue o código:

```php
for($i = 0; $i < $exibe_vencimento['parcelas']; $i++){

    $date = (new \DateTime(($data_base).$tempo))->modify($dia_semana);

    $data_boleto = $date->format('Y-m-d');

    $boletoArray = [
		'logo'                   => realpath('./vendor/newerton/yii2-boleto-remessa/logos/748.png'),
		'dataVencimento'         => new \Carbon\Carbon($data_boleto),
		'valor'                  => $valor_boleto_final,
		'numero'                 => 1,
		'numeroDocumento'        => 1,
		'pagador'                => $pagador,
		'beneficiario'           => $beneficiario,
		'carteira'               => '1',
		'byte'                   => '1',
		'agencia'                => '0523',
		'posto'                  => '10',
		'conta'                  => '01470',
		'descricaoDemonstrativo' => ['www.e-proterra.com - Fone: (55) 3433-1826', 'Protestar em 5 dias corridos após o vencimento', $data_boleto2],
		'instrucoes'             => ['www.e-proterra.com - Fone: (55) 3433-1826', 'Protestar em 5 dias corridos após o vencimento'],
		'aceite'                 => 'N',
		'especieDoc'             => 'DM',
	];
}
```

Eu fiz um FOR pra mostrar a quantidade de boletos dependendo a quantidade de parcelas escolhidas pelo usuário, porém a data dos boletos fica sempre como a ultima, digamos que foram 3 boeltos com datas 10 20 e 30, todos boletos ao inves de terem datas nessa sequencia, tem data 30. Saberiam me dizer o que é?

**Comment by newerton** [comment]
A $data_boleto está retornando as datas que você precisa?

O que você está retornando em $dia_semana?

**Comment by nicholaskr** [comment]
Sim, o $data_boleto me retorna todas as datas corretamente, e o $dia_semana busca no cadastro do cliente  que dia ele tem preferência para pagamento (alguns clientes pagam em dias especificos da semana).

**Comment by nicholaskr** [comment]
Eu ja fiz o echo mostrando o "new \Carbon\Carbon($data_boleto)" fora do array do boleto e mostra todas as datas como deveria.

**Comment by newerton** [comment]
Qual o banco que você está usando?

**Comment by nicholaskr** [comment]
mysqli

**Comment by nicholaskr** [comment]
Sicredi

**Comment by newerton** [comment]
Olhei no código do banco está normal, faz um teste ae.

```php
for($i = 0; $i < $exibe_vencimento['parcelas']; $i++){

    $date = (new \DateTime(($data_base).$tempo))->modify($dia_semana);

    $data_boleto = $date->format('Y-m-d');

    $boletoArray[] = [
		'logo'                   => realpath('./vendor/newerton/yii2-boleto-remessa/logos/748.png'),
		'dataVencimento'         => new \Carbon\Carbon($data_boleto),
		'valor'                  => $valor_boleto_final,
		'numero'                 => 1,
		'numeroDocumento'        => 1,
		'pagador'                => $pagador,
		'beneficiario'           => $beneficiario,
		'carteira'               => '1',
		'byte'                   => '1',
		'agencia'                => '0523',
		'posto'                  => '10',
		'conta'                  => '01470',
		'descricaoDemonstrativo' => ['www.e-proterra.com - Fone: (55) 3433-1826', 'Protestar em 5 dias corridos após o vencimento', $data_boleto2],
		'instrucoes'             => ['www.e-proterra.com - Fone: (55) 3433-1826', 'Protestar em 5 dias corridos após o vencimento'],
		'aceite'                 => 'N',
		'especieDoc'             => 'DM',
	];
}

echo '<pre>';
print_r($boletoArray);
echo '</pre>';
```

Me mostra como está o array.

No AbstractBoleto o código está assim.
```php
// Marca a data de vencimento para daqui a 5 dias, caso não especificada
if (!$this->getDataVencimento()) {
    $this->setDataVencimento(new Carbon(date('Y-m-d', strtotime('+5 days'))));
}
```

**Comment by nicholaskr** [comment]
Sim, assim funciona, meu problema está aqui:

`if($exibe_vencimento['parcelas'] == '1'){

$boleto = new \Newerton\Yii2Boleto\Boleto\Banco\Sicredi($boletoArray);

$pdf = new Newerton\Yii2Boleto\Boleto\Render\Pdf();
$pdf->addBoleto($boleto);
$pdf->hideInstrucoes();
$pdf->gerarBoleto($pdf::OUTPUT_SAVE, './boletos/sicredi/boleto.pdf');
echo "<script>window.open('./boletos/sicredi/boleto.pdf', '_new');</script>";
echo "Uma Parcela";

}else if($exibe_vencimento['parcelas'] > '1'){

$boletos = new \Newerton\Yii2Boleto\Boleto\Banco\Sicredi($boletoArray);

$pdf = new \Newerton\Yii2Boleto\Boleto\Render\Pdf();
if($exibe_vencimento['parcelas'] == '2'){
$pdf->addBoletos([$boletos, $boletos]);
}
if($exibe_vencimento['parcelas'] == '3'){
$pdf->addBoletos([$boletos, $boletos, $boletos]);
}
if($exibe_vencimento['parcelas'] == '4'){
$pdf->addBoletos([$boletos, $boletos, $boletos, $boletos]);
}
$pdf->hideInstrucoes();				
$pdf->gerarBoleto($pdf::OUTPUT_SAVE, './boletos/sicredi/boletoss.pdf');
echo "<script>window.open('./boletos/sicredi/boletoss.pdf', '_new');</script>";
echo "Várias Parcelas";



}`

**Comment by nicholaskr** [comment]
Tem ifs informando que se for uma parcela ele gera o boleto com o "addboleto" e se for mais de uma gera o "addboletos"
